# Generated by Django 3.2.6 on 2021-08-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='noOfViews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
